export const POLICIES = {
  // USERS
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_VIEW_SELF: "USER_VIEW_SELF",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  // NHÂN VIÊN
  NHANVIEN_VIEW_ALL: "NHANVIEN_VIEW_ALL",
  NHANVIEN_VIEW_SELF: "NHANVIEN_VIEW_SELF",
  NHANVIEN_CREATE: "NHANVIEN_CREATE",
  NHANVIEN_UPDATE: "NHANVIEN_UPDATE",
  NHANVIEN_DELETE: "NHANVIEN_DELETE",

  // KHÁCH HÀNG
  KHACHHANG_VIEW_ALL: "KHACHHANG_VIEW_ALL",
  KHACHHANG_VIEW_SELF: "KHACHHANG_VIEW_SELF",
  KHACHHANG_CREATE: "KHACHHANG_CREATE",
  KHACHHANG_UPDATE: "KHACHHANG_UPDATE",
  KHACHHANG_DELETE: "KHACHHANG_DELETE",

  // ✅ DANH MỤC (BẮT BUỘC PHẢI CÓ)
  DANHMUC_VIEW_ALL: "DANHMUC_VIEW_ALL",
  DANHMUC_VIEW_SELF: "DANHMUC_VIEW_SELF",
  DANHMUC_CREATE: "DANHMUC_CREATE",
  DANHMUC_UPDATE: "DANHMUC_UPDATE",
  DANHMUC_DELETE: "DANHMUC_DELETE",

  // SẢN PHẨM
  SANPHAM_VIEW_ALL: "SANPHAM_VIEW_ALL",
  SANPHAM_VIEW_ONE: "SANPHAM_VIEW_ONE",
  SANPHAM_CREATE: "SANPHAM_CREATE",
  SANPHAM_UPDATE: "SANPHAM_UPDATE",
  SANPHAM_DELETE: "SANPHAM_DELETE",
};
