import { POLICIES } from "../utils/constants/policies.js";

export const rolePolicyMap = {
  // ================= ADMIN =================
  admin: [
    // USERS
    POLICIES.USER_VIEW_ALL,
    POLICIES.USER_VIEW_SELF,
    POLICIES.USER_CREATE,
    POLICIES.USER_UPDATE,
    POLICIES.USER_DELETE,

    // NHÂN VIÊN
    POLICIES.NHANVIEN_VIEW_ALL,
    POLICIES.NHANVIEN_VIEW_SELF,
    POLICIES.NHANVIEN_CREATE,
    POLICIES.NHANVIEN_UPDATE,
    POLICIES.NHANVIEN_DELETE,

    // KHÁCH HÀNG
    POLICIES.KHACHHANG_VIEW_ALL,
    POLICIES.KHACHHANG_VIEW_SELF,
    POLICIES.KHACHHANG_CREATE,
    POLICIES.KHACHHANG_UPDATE,
    POLICIES.KHACHHANG_DELETE,

    // DANH MỤC
    POLICIES.DANHMUC_VIEW_ALL,
    POLICIES.DANHMUC_VIEW_SELF,
    POLICIES.DANHMUC_CREATE,
    POLICIES.DANHMUC_UPDATE,
    POLICIES.DANHMUC_DELETE,

    // ===== SẢN PHẨM (TOÀN QUYỀN) =====
    POLICIES.SANPHAM_VIEW_ALL,
    POLICIES.SANPHAM_VIEW_ONE,
    POLICIES.SANPHAM_CREATE,
    POLICIES.SANPHAM_UPDATE,
    POLICIES.SANPHAM_DELETE,
  ],

  // ================= NHÂN VIÊN =================
  nhanvien: [
    // USERS
    POLICIES.USER_VIEW_SELF,

    // ❌ KHÔNG có NHANVIEN_VIEW_ALL
    POLICIES.NHANVIEN_VIEW_SELF,
    POLICIES.NHANVIEN_UPDATE,

    // ===== KHÁCH HÀNG (TOÀN QUYỀN) =====
    POLICIES.KHACHHANG_VIEW_ALL,
    POLICIES.KHACHHANG_VIEW_SELF,
    POLICIES.KHACHHANG_CREATE,
    POLICIES.KHACHHANG_UPDATE,
    POLICIES.KHACHHANG_DELETE,

    // ===== DANH MỤC (TOÀN QUYỀN) =====
    POLICIES.DANHMUC_VIEW_ALL,
    POLICIES.DANHMUC_VIEW_SELF,
    POLICIES.DANHMUC_CREATE,
    POLICIES.DANHMUC_UPDATE,
    POLICIES.DANHMUC_DELETE,

    // ===== SẢN PHẨM (TOÀN QUYỀN) =====
    POLICIES.SANPHAM_VIEW_ALL,
    POLICIES.SANPHAM_VIEW_ONE,
    POLICIES.SANPHAM_CREATE,
    POLICIES.SANPHAM_UPDATE,
    POLICIES.SANPHAM_DELETE,
  ],

  // ================= KHÁCH HÀNG =================
  khachhang: [
    POLICIES.KHACHHANG_VIEW_SELF,
    POLICIES.KHACHHANG_UPDATE,
    // ===== DANH MỤC (TOÀN QUYỀN) =====
    POLICIES.DANHMUC_VIEW_ALL,
    POLICIES.DANHMUC_VIEW_SELF,
    // ===== SẢN PHẨM (TOÀN QUYỀN) =====
    POLICIES.SANPHAM_VIEW_ALL,
    POLICIES.SANPHAM_VIEW_ONE,
  ],
};
